<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Back</name>
   <tag></tag>
   <elementGuidId>e41ea2a5-7d73-45b5-8f4a-7f630f711add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.widget.ImageView' and @content-desc = 'imgBack']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.ImageView</value>
      <webElementGuid>a6fab807-739d-4e52-bf83-58ebe7813918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>imgBack</value>
      <webElementGuid>d01cb6f2-a864-4d7f-a683-a6e8cbfaab07</webElementGuid>
   </webElementProperties>
</WebElementEntity>
