<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Tambahkan</name>
   <tag></tag>
   <elementGuidId>99f3873f-03f4-4398-8fa2-fa20f6d042d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.view.ViewGroup' and @content-desc = 'touchReminder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.ViewGroup</value>
      <webElementGuid>5abbed4f-b6c9-4191-9ca6-e68a7cbe607d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>touchReminder</value>
      <webElementGuid>1f4d0456-cc87-40fc-9740-610a37e4f9b1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
