<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Navbar_Rekaman</name>
   <tag></tag>
   <elementGuidId>a5a6ed77-ee31-43f4-b0a6-8e2733045649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.widget.TextView' and (text() = 'Rekaman' or . = 'Rekaman')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>b9575c59-5222-4f96-8b3b-af613bef6aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rekaman</value>
      <webElementGuid>48d95fe4-59f2-4d83-a0a9-103d2fc3bed0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
