<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Navbar_Belanja</name>
   <tag></tag>
   <elementGuidId>cb93e040-dde8-46b3-b728-5c38afa21604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.widget.TextView' and (text() = 'Belanja' or . = 'Belanja')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>1e2b8d82-f9ad-4f1a-b88f-36bd59c9d210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belanja</value>
      <webElementGuid>641e20c1-aa3a-4fe2-8f5a-3e04380fb1ab</webElementGuid>
   </webElementProperties>
</WebElementEntity>
