<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BangunTidur_TextField_ApaSnackMalamAnda</name>
   <tag></tag>
   <elementGuidId>2eb52e3e-4319-4236-9833-676c7a6ac614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.widget.EditText' and @content-desc = 'inputFood2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.EditText</value>
      <webElementGuid>cfab86a9-f18b-4c06-9d24-0b175b9cbe5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>inputFood2</value>
      <webElementGuid>337c8e68-b396-44ce-bee6-7bee8c8c494b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
